name: CI Horizon

on:
  push:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-horizon-${{ github.ref }}
  cancel-in-progress: true

jobs:
  wrapper-validation:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate Wrapper
        uses: gradle/wrapper-validation-action@v2

  horizon-build:
    name: Build Horizon flavors
    runs-on: ubuntu-latest
    needs: wrapper-validation
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install required SDK packages
        run: |
          sdkmanager --install \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0"
          yes | sdkmanager --licenses

      - name: Build Horizon variants
        run: ./gradlew --stacktrace --no-daemon :openiap:assembleHorizonDebug :Example:assembleHorizonDebug
